name: Provenance
on:
  push:
    tags: ['v*']

permissions:
  contents: read
  id-token: write

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20.11.1'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Generate provenance
        run: npx ts-node ./scripts/generate-provenance.ts
      - name: Verify integrity
        env:
          TS_NODE_FILES: 'true'
          TS_NODE_TRANSPILE_ONLY: 'true'
        run: node --loader ts-node/esm ./scripts/integrity-check.ts --provenance-file ./provenance.json --require-provenance --require-signature --provenance-signature ./provenance.sig --provenance-public-key ./provenance.pub
