name: Publish
on:
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
        with:
          node-version: '20.11.1'
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Preview publish
        run: npx ts-node ./scripts/publish-preview.ts
